services:
  api:
    build: .
    container_name: "api"
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
       MINIO_ENDPOINT: "${MINIO_ENDPOINT:-minio:9000}"
       MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minio_root}"
       MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-minio_password}"

       CLOUD_MINIO_ENDPOINT: "${CLOUD_MINIO_ENDPOINT:-host.docker.internal:9100}"
       CLOUD_MINIO_ACCESS_KEY: "${CLOUD_MINIO_ACCESS_KEY:-minio_root}"
       CLOUD_MINIO_SECRET_KEY: "${CLOUD_MINIO_SECRET_KEY:-minio_password}"
       CLOUD_MINIO_SECURE: "${CLOUD_MINIO_SECURE:-false}"
       
       SYNC_INTERVAL_SEC: "${SYNC_INTERVAL_SEC:-20}"
  mysql:
    image: "mysql:8.0"
    container_name: "mysql_poc1"
    environment:
      MYSQL_DATABASE: "sample_db"
      MYSQL_USER: "sample_user"
      MYSQL_PASSWORD: "sample_password"
      MYSQL_ROOT_PASSWORD: "p@assw0rd"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    container_name: "phpmyadmin_poc1"
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "root"
      PMA_PASSWORD: "p@assw0rd"
    depends_on:
      - mysql
    ports:
      - "8082:80"
  minio:
    container_name: "minio_poc1"
    image: "minio/minio:RELEASE.2025-07-23T15-54-02Z"
    ports:
      - "9000:9000" # API用
      - "9001:9001" # コンソール画面用
    env_file:
      - ./.env
    environment:
       MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minio_root}"
       MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minio_password}"
       MINIO_NOTIFY_WEBHOOK_ENABLE_FASTAPI: "${MINIO_NOTIFY_WEBHOOK_ENABLE_FASTAPI:-on}"
       MINIO_NOTIFY_WEBHOOK_ENDPOINT_FASTAPI: "${MINIO_NOTIFY_WEBHOOK_ENDPOINT_FASTAPI:-http://api:8000/minio/webhook}"
    command: server --console-address ":9001" /export
    volumes:
      - ./docker/minio/data:/export
  mc:
    image: "minio/mc:RELEASE.2025-07-21T05-28-08Z"
    depends_on: [minio, api]
    entrypoint: ["/bin/sh", "-lc"]
    command: |
      "mc alias set local http://minio:9000 minio_root minio_password &&
       tail -f /dev/null &&
       mc anonymous set public local/local-point-cloud
      "
volumes:
  mysql_data:
