DROP SCHEMA IF EXISTS poc1_db;
CREATE SCHEMA poc1_db;
USE poc1_db;

DROP TABLE IF EXISTS upload_history;

CREATE TABLE upload_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  geohash VARCHAR(20) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  create_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
