global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['cloud-prometheus:9090']
  - job_name: 'app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['cloud_api_poc1:8100']
