version: "3.0"

services:
  api:
    container_name: "api"
    build: .
    volumes:
      - "./app:/app"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: pgpointcloud/pointcloud:latest
    environment:
      - POSTGRES_DB=pointclouds
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5643:5643"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
